sudo: required
services:
  - docker

before_install:
  - docker build -t pipal/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pipal/react-test npm test

after_success:
  - docker build -t pipal/multi-client ./client
  - docker build -t pipal/multi-nginx ./nginx
  - docker build -t pipal/multi-server ./server
  - docker build -t pipal/multi-worker ./worker
  # Take and push to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push pipal/multi-client
  - docker push pipal/multi-nginx
  - docker push pipal/multi-server
  - docker push pipal/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-735836341192"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"